# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detail_course.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(845, 539)
        MainWindow.setStyleSheet("QPushButton:pushButton {\n"
"    background-color:rgb(63, 1, 255);\n"
"    color:\"white\"\n"
"}\n"
"\n"
"QWidget{\n"
"    background-color:rgb(24, 1, 86);\n"
"    border-radius:3%\n"
"}\n"
"\n"
"QGroupBox{\n"
"    background-color:\"white\"\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(17, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 40))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 33))
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_back = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_back.sizePolicy().hasHeightForWidth())
        self.btn_back.setSizePolicy(sizePolicy)
        self.btn_back.setMinimumSize(QtCore.QSize(81, 31))
        self.btn_back.setMaximumSize(QtCore.QSize(81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_back.setFont(font)
        self.btn_back.setStyleSheet("QPushButton{\n"
"    background-color:#b5ffd9;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:#a5f0cc;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:#a0d6b9;\n"
"}")
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayout_4.addWidget(self.btn_back)
        spacerItem2 = QtWidgets.QSpacerItem(16777215, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setMaximumSize(QtCore.QSize(181, 27))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("QLabel{\n"
"    color:\"white\"\n"
"}")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        spacerItem3 = QtWidgets.QSpacerItem(16777215, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.label_saldo = QtWidgets.QLabel(self.frame)
        self.label_saldo.setMinimumSize(QtCore.QSize(131, 26))
        self.label_saldo.setMaximumSize(QtCore.QSize(131, 26))
        self.label_saldo.setStyleSheet("QLabel{\n"
"    background-color:\"white\"\n"
"}")
        self.label_saldo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_saldo.setObjectName("label_saldo")
        self.horizontalLayout_4.addWidget(self.label_saldo)
        self.verticalLayout_5.addWidget(self.frame)
        spacerItem4 = QtWidgets.QSpacerItem(720, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem4)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 221))
        self.groupBox.setStyleSheet("QWidget {\n"
"    background-color:\"white\"\n"
"}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout.setSpacing(20)
        self.img_course = QtWidgets.QLabel(self.groupBox)
        self.img_course.setMinimumSize(QtCore.QSize(151, 192))
        self.img_course.setMaximumSize(QtCore.QSize(151, 192))
        self.img_course.setObjectName("img_course")
        self.horizontalLayout.addWidget(self.img_course)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_nama_course = QtWidgets.QLabel(self.groupBox)
        self.label_nama_course.setMinimumSize(QtCore.QSize(419, 51))
        self.label_nama_course.setMaximumSize(QtCore.QSize(16777215, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_nama_course.setFont(font)
        self.label_nama_course.setObjectName("label_nama_course")
        self.verticalLayout_2.addWidget(self.label_nama_course)
        self.label_deskripsi_course = QtWidgets.QLabel(self.groupBox)
        self.label_deskripsi_course.setMinimumSize(QtCore.QSize(0, 96))
        self.label_deskripsi_course.setMaximumSize(QtCore.QSize(16777215, 144))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_deskripsi_course.setFont(font)
        self.label_deskripsi_course.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_deskripsi_course.setWordWrap(True)
        self.label_deskripsi_course.setObjectName("label_deskripsi_course")
        self.verticalLayout_2.addWidget(self.label_deskripsi_course)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_harga_course = QtWidgets.QLabel(self.groupBox)
        self.label_harga_course.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_harga_course.setFont(font)
        self.label_harga_course.setObjectName("label_harga_course")
        self.verticalLayout.addWidget(self.label_harga_course)
        self.btn_beli = QtWidgets.QPushButton(self.groupBox)
        self.btn_beli.setMinimumSize(QtCore.QSize(119, 31))
        self.btn_beli.setMaximumSize(QtCore.QSize(119, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_beli.setFont(font)
        self.btn_beli.setStyleSheet("QPushButton {\n"
"    background-color:#3f01ff;\n"
"    color:#fff;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#3000e0;\n"
"    color:#fff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:#2000c0;\n"
"    color:#fff;\n"
"}")
        self.btn_beli.setObjectName("btn_beli")
        self.verticalLayout.addWidget(self.btn_beli)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_2.setStyleSheet("QWidget {\n"
"    background-color:\"white\"\n"
"}")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(12, 5, 8, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setMinimumSize(QtCore.QSize(101, 26))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 26))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_rating_course = QtWidgets.QLabel(self.groupBox_2)
        self.label_rating_course.setMinimumSize(QtCore.QSize(71, 0))
        self.label_rating_course.setMaximumSize(QtCore.QSize(16777215, 26))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_rating_course.setFont(font)
        self.label_rating_course.setObjectName("label_rating_course")
        self.horizontalLayout_2.addWidget(self.label_rating_course)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.btn_berikan_tanggapan = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_berikan_tanggapan.setMinimumSize(QtCore.QSize(170, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_berikan_tanggapan.setFont(font)
        self.btn_berikan_tanggapan.setStyleSheet("QPushButton{\n"
"    background-color:#b5ffd9;\n"
"    border : 1px solid black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:#a5f0cc;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:#a0d6b9;\n"
"}")
        self.btn_berikan_tanggapan.setObjectName("btn_berikan_tanggapan")
        self.horizontalLayout_2.addWidget(self.btn_berikan_tanggapan)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox_2)
        self.scrollArea.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 755, 116))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollArea)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 845, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_back.setText(_translate("MainWindow", "Kembali"))
        self.label_9.setText(_translate("MainWindow", "Detail Course"))
        self.label_saldo.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Saldo: Rp. xxx.xxx</span></p></body></html>"))
        self.label_nama_course.setText(_translate("MainWindow", "Nama Course"))
        self.label_deskripsi_course.setText(_translate("MainWindow", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et viverra sem. Quisque fermentum sem ac purus tincidunt, at lacinia ex tincidunt. Donec volutpat, tortor ac hendrerit hendrerit, felis velit maximus felis, at ultrices mi neque vel ante. Vestibulum efficitur nec velit id efficitur. Curabitur at ipsum non turpis euismod pulvinar. Duis sollicitudin enim vitae enim egestas, elementum finibus enim rutrum. Donec nec enim at arcu gravida semper nec a nisi. Aenean mollis sollicitudin ligula, a sodales justo cursus in. Nam eu blandit sem. Phasellus vitae lobortis ex, ornare pulvinar leo."))
        self.label_harga_course.setText(_translate("MainWindow", "Rp. xxx.xxx"))
        self.btn_beli.setText(_translate("MainWindow", "Beli Course"))
        self.label_4.setText(_translate("MainWindow", "Review"))
        self.label_rating_course.setText(_translate("MainWindow", "⭐ 4.3"))
        self.btn_berikan_tanggapan.setText(_translate("MainWindow", "Berikan Rating dan Review"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
