# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'isi_saldo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(891, 641)
        MainWindow.setStyleSheet("QMainWindow{\n"
"background-color:rgb(24, 1, 86)\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget{\n"
"background-color:rgb(24, 1, 86)\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 48, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(411, 261))
        self.groupBox_2.setMaximumSize(QtCore.QSize(411, 261))
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"background-color:\"white\";\n"
"border-radius: 5%;\n"
"border: 1px solid black\n"
"\n"
"}\n"
"\n"
"QWidget{\n"
"background-color:white\n"
"}\n"
"")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox.setGeometry(QtCore.QRect(30, 50, 351, 151))
        self.groupBox.setStyleSheet("QGroupBox {\n"
"background-color:\"white\";\n"
"border-radius: 5%;\n"
"border:1px solid black\n"
"}\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(50, 20, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(50, 80, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.if_saldo_add = QtWidgets.QLineEdit(self.groupBox)
        self.if_saldo_add.setGeometry(QtCore.QRect(50, 100, 261, 24))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.if_saldo_add.setFont(font)
        self.if_saldo_add.setStyleSheet("QLineEdit {\n"
"    background-color: #c8c4c4;\n"
"    border-radius:5%;\n"
"}")
        self.if_saldo_add.setObjectName("if_saldo_add")
        self.tf_saldo = QtWidgets.QLabel(self.groupBox)
        self.tf_saldo.setGeometry(QtCore.QRect(50, 40, 111, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.tf_saldo.setFont(font)
        self.tf_saldo.setStyleSheet("color: rgb(0, 0, 127);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.tf_saldo.setText("")
        self.tf_saldo.setObjectName("tf_saldo")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(150, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.btn_pay = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_pay.setGeometry(QtCore.QRect(310, 220, 75, 23))
        self.btn_pay.setStyleSheet("QPushButton {\n"
"    background-color: #c8c4c4;\n"
"    border-style: outset;\n"
"    padding: 2px;\n"
"    border-radius: 5%;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color:#3f01ff;\n"
"    color:#fff;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#3000e0;\n"
"    color:#fff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:#2000c0;\n"
"    color:#fff;\n"
"}")
        self.btn_pay.setObjectName("btn_pay")
        self.btn_cancel = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_cancel.setGeometry(QtCore.QRect(30, 220, 75, 23))
        self.btn_cancel.setStyleSheet("QPushButton{\n"
"background-color:#b5ffd9;\n"
"border: none;\n"
"border-radius: 4px;\n"
"border: 1px solid black;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#a5f0cc;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:#a0d6b9;\\n\"\n"
"}\n"
"")
        self.btn_cancel.setObjectName("btn_cancel")
        self.verticalLayout.addWidget(self.groupBox_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 891, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Saldo anda saat ini:"))
        self.label_2.setText(_translate("MainWindow", "Nominal pengisian:"))
        self.label_3.setText(_translate("MainWindow", "Isi Saldo"))
        self.btn_pay.setText(_translate("MainWindow", "Bayar"))
        self.btn_cancel.setText(_translate("MainWindow", "Batal"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
